-- 코드를 입력하세요
SELECT T1.CART_ID
FROM (SELECT CART_ID
      FROM CART_PRODUCTS
      WHERE NAME = "Yogurt"
     ) AS T1
     JOIN (SELECT CART_ID
          FROM CART_PRODUCTS
          WHERE NAME = "Milk"
          ) AS T2 ON T1.CART_ID = T2.CART_ID
GROUP BY T1.CART_ID
ORDER BY T1.CART_ID